stages:
  - build
  - build-chromium
  - publish
  - test

image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  NAMESPACE: themephlox/gitlab-ci-pipeline-php-7.1
  CI_REGISTRY_USER: "themephlox"
  CI_REGISTRY_PASSWORD: "@KZaH*v88i#!WqT"

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"

FPM 7.3:
  stage: build
  variables:
    IMAGE_VERSION: "7.3-fpm"
  script:
    - docker pull php:$IMAGE_VERSION || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/7.3/fpm/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html $NAMESPACE:$IMAGE_VERSION goss -g tests/goss-7.3.yaml v
    - docker push $NAMESPACE:$IMAGE_VERSION
  when: always

FPM 7.1:
  stage: build
  variables:
    IMAGE_VERSION: "7.1-fpm"
  script:
    - docker pull php:$IMAGE_VERSION || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/7.1/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html $NAMESPACE:$IMAGE_VERSION goss -g tests/goss-7.1.yaml v
    - docker push $NAMESPACE:$IMAGE_VERSION
  when: always
